/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'laserstream-napi.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./laserstream-napi.win32-x64-msvc.node')
          } else {
            nativeBinding = require('helius-laserstream-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
      case 'arm64':
        throw new Error(`Unsupported architecture on Windows: ${arch}. Only x64 is supported.`)
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}. Only x64 is supported.`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'laserstream-napi.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./laserstream-napi.darwin-universal.node')
      } else {
        nativeBinding = require('helius-laserstream-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'laserstream-napi.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./laserstream-napi.darwin-x64.node')
          } else {
            nativeBinding = require('helius-laserstream-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'laserstream-napi.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./laserstream-napi.darwin-arm64.node')
          } else {
            nativeBinding = require('helius-laserstream-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}. Only x64 and arm64 are supported.`)
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          throw new Error(`Musl libc is not supported. Please use a glibc-based Linux distribution like Ubuntu, Debian, CentOS, or RHEL.`)
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'laserstream-napi.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./laserstream-napi.linux-x64-gnu.node')
            } else {
              nativeBinding = require('helius-laserstream-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
      case 'arm':
        throw new Error(`Unsupported architecture on Linux: ${arch}. Only x64 is supported.`)
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}. Only x64 is supported.`)
    }
    break
  case 'android':
  case 'freebsd':
    throw new Error(`Unsupported platform: ${platform}. Supported platforms are macOS, Windows, and Linux.`)
  default:
    throw new Error(`Unsupported OS: ${platform}. Supported platforms are macOS (darwin), Windows (win32), and Linux.`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { shutdownAllStreams, getActiveStreamCount, CommitmentLevel, LaserstreamClient, StreamHandle } = nativeBinding

module.exports.shutdownAllStreams = shutdownAllStreams
module.exports.getActiveStreamCount = getActiveStreamCount
module.exports.CommitmentLevel = CommitmentLevel
module.exports.LaserstreamClient = LaserstreamClient
module.exports.StreamHandle = StreamHandle
