/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum CommitmentLevel {
  Processed = 0,
  Confirmed = 1,
  Finalized = 2
}
export declare class LaserstreamClient {
  constructor(endpoint: string, token?: string | undefined | null, maxReconnectAttempts?: number | undefined | null)
  subscribe(request: any, callback: (error: Error | null, buffer: Buffer) => void): Promise<StreamHandle>
}
export declare class StreamHandle {
  id: string
  cancel(): void
}
