/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface GetSlotResponse {
  slot: string
}
export interface GetBlockHeightResponse {
  blockHeight: string
}
export interface GetLatestBlockhashResponse {
  slot: string
  blockhash: string
  lastValidBlockHeight: string
}
export interface IsBlockhashValidResponse {
  slot: string
  valid: boolean
}
export interface GetVersionResponse {
  version: string
}
export interface PongResponse {
  count: number
}
export interface SubscribeReplayInfoResponse {
  firstAvailable?: string
}
export declare function shutdownAllStreams(): void
export declare function getActiveStreamCount(): number
export const enum CommitmentLevel {
  PROCESSED = 0,
  CONFIRMED = 1,
  FINALIZED = 2
}
/**
 * Native client for unary RPCs. All calls share one HTTP/2 connection, opened
 * on the first call and re-opened automatically if it drops.
 */
export declare class UnaryClient {
  constructor(endpoint: string, token?: string | undefined | null, channelOptions?: object | undefined | null, timeoutMs?: number | undefined | null)
  /**
   * Drops the shared connection. Calls already in flight finish normally;
   * a later call opens a new connection.
   */
  close(): void
  getSlot(commitment?: number | undefined | null): Promise<GetSlotResponse>
  getBlockHeight(commitment?: number | undefined | null): Promise<GetBlockHeightResponse>
  getLatestBlockhash(commitment?: number | undefined | null): Promise<GetLatestBlockhashResponse>
  isBlockhashValid(blockhash: string, commitment?: number | undefined | null): Promise<IsBlockhashValidResponse>
  getVersion(): Promise<GetVersionResponse>
  ping(count?: number | undefined | null): Promise<PongResponse>
  /**
   * Oldest slot this endpoint can replay from (smallest usable `fromSlot`).
   * See `LaserstreamClient.subscribeReplayInfo` in client.d.ts for usage.
   */
  subscribeReplayInfo(): Promise<SubscribeReplayInfoResponse>
}
export declare class LaserstreamClient {
  constructor(endpoint: string, token?: string | undefined | null, maxReconnectAttempts?: number | undefined | null, channelOptions?: object | undefined | null, replay?: boolean | undefined | null)
  subscribe(request: any, callback: (error: Error | null, updateBytes: Uint8Array) => void): Promise<StreamHandle>
  subscribePreprocessed(request: any, callback: (error: Error | null, updateBytes: Uint8Array) => void): Promise<StreamHandle>
}
export declare class StreamHandle {
  id: string
  cancel(): void
  write(request: any): void
}
